# Generated by Django 3.1.5 on 2022-03-05 17:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default.jpg', upload_to=users.models.upload_to),
        ),
    ]
