# Generated by Django 3.1.5 on 2022-03-11 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent']},
        ),
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
