# Generated by Django 3.1.5 on 2022-03-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220310_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent']},
        ),
    ]
